#:schema node_modules/wrangler/config-schema.json
name = "loki-api-hub"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "loki-db-prod"
database_id = "SEU_DATABASE_ID_AQUI" # Gerado ao rodar 'npx wrangler d1 create loki-db-prod'

[[kv_namespaces]]
binding = "SESSIONS"
id = "SEU_KV_NAMESPACE_ID_AQUI" # Gerado ao rodar 'npx wrangler kv:namespace create loki-kv-sessions'

[[r2_buckets]]
binding = "PAYLOADS"
bucket_name = "loki-r2-payloads"
