#:schema node_modules/wrangler/config-schema.json
name = "loki-api-hub"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "loki-db-prod"
database_id = "50816303-3353-45dd-9b31-d85d65ff138a" # Gerado ao rodar 'npx wrangler d1 create loki-db-prod'

[[kv_namespaces]]
binding = "SESSION"
id = "94f3d1f376cd4986988e9c3f346e011d" # Gerado ao rodar 'npx wrangler kv:namespace create loki-kv-sessions'

[[r2_buckets]]
binding = "PAYLOADS"
bucket_name = "loki-r2-payloads"
